angular.module('newApp',
    [
        'routerApp',
        'studentCtrl',
        'studentService',
        'homeService',
        'homeCtrl',
        'loginCtrl',
        'loginService',
        'questionCtrl',
        'questionService',
        'answerCtrl',
        'answerService'
    ]
);